set:
  features_train: false
  features_test: false
  train: false
  eval: false
  gpus: 1
  data: bioacoustics
  n_dim: 128

path:
  root_dir: /home/mark/projects/DCASE2021
  data_dir: /home/mark/ssd/protonets/${set.data}/data
  train_dir: ${path.data_dir}/Development_Set/Training_Set
  val_dir: ${path.data_dir}/Development_Set/Validation_Set
  test_dir: ${path.data_dir}/Development_Set/Validation_Set
  feat_path: /home/mark/ssd/protonets/${set.data}/features
  train_feat: ${path.feat_path}/feat_train
  eval_feat: ${path.feat_path}/feat_eval
  test_feat: ${path.feat_path}/feat_test
  model: ${path.root_dir}/models
  best_model: ${path.model}/best_*_${set.data}.ckpt
  last_model: ${path.model}/latest_*_${set.data}.ckpt

features:
  freq_mask: 10
  time_mask: 10
  time_stretch: 1.1
  seg_len: 1.0
  hop_seg: 0.25
  sample_rate: 16000
  fmin: 800
  n_mels: 80
  n_fft: 512
  hop: 128
  frontend: PCEN
  aug_train: true

train:
  n_shot: 5
  k_way: 10
  epochs: 250
  lr: 0.0001
  momentum: 0.85
  factor: 0.5
  threshold: 0.001
  patience: 10
  distance: euclidean
  norm: false

eval:
  samples_neg: 512
  iterations: 3
  query_batch_size: 8
  query_set_size: null
  negative_set_batch_size: 16
  threshold: 0.5

post_proc:
  path: ${path.val_dir}
  threshold: 0.6
